-- SQL Retail Sales Analysis - P1

CREATE DATABASE sql_project_p2;

-- Create Table
DROP  TABLE IF EXISTS retail_sales;
CREATE TABLE retail_sales
			(
				transactions_id	INT PRIMARY KEY,
				sale_date DATE,
				sale_time TIME,
				customer_id INT,
				gender VARCHAR(15),
				age	INT,
				category VARCHAR(15),
				quantity INT,
				price_per_unit FLOAT,
				cogs FLOAT,
				total_sale FLOAT
			);

SELECT * FROM retail_sales;

SELECT 
	count(*) 
FROM retail_sales;


--Data Cleaning

-- To Check any columns has NULL values

SELECT * FROM retail_sales
WHERE transactions_id IS NULL;

SELECT * FROM retail_sales
WHERE sale_date IS NULL;

SELECT * FROM retail_sales
WHERE sale_time IS NULL;

SELECT * FROM retail_sales
WHERE customer_id IS NULL;

SELECT * FROM retail_sales
WHERE 
	transactions_id IS NULL
	OR
	sale_date IS NULL
	OR
	gender IS NULL
	OR
	category IS NULL
	OR
	quantity IS NULL
    OR
	price_per_unit IS NULL
    OR
	cogs IS NULL
    OR
	total_sale IS NULL;

-- Delete NULL values

DELETE FROM retail_sales
WHERE 
	transactions_id IS NULL
	OR
	sale_date IS NULL
	OR
	gender IS NULL
	OR
	category IS NULL
	OR
	quantity IS NULL
    OR
	price_per_unit IS NULL
    OR
	cogs IS NULL
    OR
	total_sale IS NULL;

-- Data Exploration

--How many sales we have?
SELECT COUNT(*) as total_sale from retail_sales;

--How many customers we have?
SELECT COUNT(DISTINCT customer_id)as total_sale from retail_sales;

SELECT DISTINCT category FROM retail_sales;

-- Data Analysis & Business Key Problems & Answers

-- Q1 Write a SQL query to retrive all columns for sales made on '2022-11-05' 

SELECT * 
FROM retail_sales
WHERE sale_date = '2022-11-05';

--Q2. Write a SQL query to retrive all transacdtions where the category and the quantity sold is more than 4 in the month of NOV-2022

SELECT 
*
FROM retail_sales
WHERE 
	category = 'Clothing'
	AND
	TO_CHAR(sale_date, 'YYYY-MM') ='2022-11'
	AND
	quantity >=4;

-- Q3. Write a SQL query to calculate the total sales (toatal_sale) for each category.

SELECT 
	category,
	SUM(total_sale) as net_sale,
	COUNT(*) as total_orders
FROM retail_sales
GROUP BY 1;

--Q4. Write a SQL query to find the average age of cutomers who purchased items from the 'Beauty' category.

SELECT
	ROUND(AVG(age),2) as avg_age
FROM retail_sales
WHERE category = 'Beauty';

--Q5. Write a SQL query to find all transactions where the total_sale is greater than 1000.

SELECT * FROM retail_sales
WHERE total_sale >=1000;

--Q6. Write a SQL query to find the total number of transactions(transaction_id) made by each gender in each category

select 
	category,
	gender,
	COUNT(*) as total_trans
from retail_sales
GROUP BY category,gender;

--Q7. Write a SQL query to calculate the average sale for each month. Find out best selling month in each year.

SELECT 
	year,
	month,
	avg_sale
FROM
(
	SELECT
		EXTRACT(YEAR from sale_date) as year,
		EXTRACT(MONTH from sale_date) as month,
		AVG(total_sale) as avg_sale,
		RANK() OVER(PARTITION BY EXTRACT(YEAR from sale_date) ORDER BY AVG(total_sale) DESC) as rank
	FROM retail_sales
	GROUP BY 1,2
) as t1
WHERE rank =1;

-- Q8. Write a SQL query to find the top 5 Customer based on the hightest total sales

SELECT 
	customer_id,
	SUM(total_sale) as total_sales
FROM retail_sales
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

-- Q9. Write a SQL query to find the number of unique cutomers who purchased items from each category.

SELECT
	category,
	COUNT(DISTINCT customer_id) as cnt_unique_cs
FROM retail_sales
GROUP BY category;

--Q10. Write a SQL to create each shift and number of orders(Example Morning <= 12, Afternoon Between 12 & 17, Evening > 17)

WITH hourly_sale
AS
(
SELECT *,
	CASE
		WHEN EXTRACT(HOUR FROM sale_time) < 12 THEN 'Morning'
		WHEN EXTRACT(HOUR FROM sale_time) BETWEEN 12 AND 17 THEN 'Afternoon'
		ELSE 'Evening'
	END as shift
FROM retail_sales
)
SELECT 
	shift,
	COUNT(*) as total_orders
FROM hourly_sale
GROUP BY shift

--Q11. Find the total revenue generated by each gender.

SELECT 
	gender,
	SUM(total_sale) as total_revenue
FROM retail_sales
GROUP BY gender
ORDER BY total_revenue DESC;

-- Q12. Find the highest priced product purchased in each category.

SELECT 
	category,
	MAX(price_per_unit) as highest_price
FROM retail_sales
GROUP BY category
ORDER BY highest_price DESC;

-- Q13. Find the day of week with highest number of sales.

SELECT
	TO_CHAR(sale_date, 'Day') as day_name,
	COUNT(*) as total_orders
FROM retail_sales
GROUP BY 1
ORDER BY total_orders DESC;

-- Q14. Calculate total revenue per age group (0–18, 19–30, 31–50, >50)

SELECT
	CASE
		WHEN age BETWEEN 0 AND 18 THEN '0-18'
		WHEN age BETWEEN 19 AND 30 THEN '19-30'
		WHEN age BETWEEN 31 AND 50 THEN '31-50'
		ELSE '50+'
	END AS age_group,
	SUM(total_sale) as revenue
FROM retail_sales
GROUP BY age_group
ORDER BY revenue DESC;

--Q15. Find the average quantity purchased per transaction for each category.

SELECT
	 category,
	 ROUND(avg(quantity),2) as avg_qty
FROM retail_sales
GROUP BY category
ORDER BY avg_qty DESC;

-- Q16. Find customers who made more than 10 purchases.

SELECT
	 customer_id,
	 COUNT(*) as total_orders
FROM retail_sales
GROUP BY customer_id
HAVING COUNT(*) > 10
ORDER BY total_orders DESC;

--Q17. Find the first purchase date of each customer.

SELECT
	customer_id,
	MIN(sale_date) as first_purchase_date
FROM retail_sales
GROUP BY customer_id
ORDER BY first_purchase_date;

--Q18. Calculate total profit per category.
--Profit = total_sale − cogs

SELECT
	 category,
	 SUM(total_sale - cogs) as total_profit
FROM retail_sales
GROUP BY category
ORDER BY total_profit DESC;

--Q19. Find the top 3 selling categories by total quantity.

SELECT 
	category,
	SUM(quantity) as total_units_sold
FROM retail_sales
GROUP BY category
ORDER BY total_units_sold DESC
LIMIT 3;

--Q20. Find total sales made during weekends (Saturday & Sunday).

SELECT
	SUM(total_sale) as weekend_sales
FROM retail_sales
WHERE EXTRACT(DOW FROM sale_date) IN (6,0);

--Q21.Find customers who have only purchased from one category.

SELECT
    customer_id,
    COUNT(DISTINCT category) AS category_count
FROM retail_sales
GROUP BY customer_id
HAVING COUNT(DISTINCT category) = 1;

--Q22. For each month, find total orders and total revenue.

SELECT
    DATE_TRUNC('month', sale_date) AS month,
    COUNT(*) AS total_orders,
    SUM(total_sale) AS total_revenue
FROM retail_sales
GROUP BY month
ORDER BY month;

--Q23. Find categories where average price per unit is greater than overall average price.

WITH overall AS (
    SELECT AVG(price_per_unit) AS avg_price FROM retail_sales
)
SELECT
    category,
    AVG(price_per_unit) AS category_avg_price
FROM retail_sales, overall
GROUP BY category, overall.avg_price
HAVING AVG(price_per_unit) > overall.avg_price;

-- Q24.Identify customers who increased their spending month-over-month.

WITH monthly_spend AS (
    SELECT
        customer_id,
        DATE_TRUNC('month', sale_date) AS month,
        SUM(total_sale) AS monthly_revenue
    FROM retail_sales
    GROUP BY customer_id, month
),
compare AS (
    SELECT
        customer_id,
        month,
        monthly_revenue,
        LAG(monthly_revenue) OVER (PARTITION BY customer_id ORDER BY month) AS previous_month_revenue
    FROM monthly_spend
)
SELECT
    customer_id,
    month,
    monthly_revenue,
    previous_month_revenue
FROM compare
WHERE previous_month_revenue IS NOT NULL
  AND monthly_revenue > previous_month_revenue
ORDER BY customer_id, month;

--Q25. Find the top 1 category per gender based on total spending.
WITH ranked AS (
    SELECT
        gender,
        category,
        SUM(total_sale) AS revenue,
        RANK() OVER (PARTITION BY gender ORDER BY SUM(total_sale) DESC) AS rnk
    FROM retail_sales
    GROUP BY gender, category
)
SELECT
    gender,
    category,
    revenue
FROM ranked
WHERE rnk = 1
ORDER BY gender;

